version: '3'

services:
  redis-stack:
    image: redis/redis-stack:latest
    volumes:
      - ./local-redis-stack.conf:/redis-stack.conf
      - ./local-data/:/data
    ports:
      - 6379:6379
      - 8001:8001

  mailhog:
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64
    ports:
      - "8025:8025"
      - "1025:1025"

  mailer:
    image: osem-mailer:latest
    env_file:
      - .env.docker
    depends_on:
      - redis-stack